### 安装 <a href="http://tushare.org/index.html">tushare</a> 
    pip install tushare

In [40]:
import tushare as ts
import matplotlib.pyplot as plt
import matplotlib.finance as mpf
import numpy as np
import talib as tl
import pandas as pd
import datetime as dt


df = ts.get_k_data('002408', ktype='60',autype="qfq",index=False)

df[["date","close"]]


#RSI
df["rsi"] = tl.RSI(df['close'].values, timeperiod=9)
df["macd"],df["signal"],df["hist"] = tl.MACD(df['close'].values, fastperiod=12, slowperiod=26, signalperiod=9)

                 date  close
0    2017-11-14 14:00  12.68
1    2017-11-14 15:00  12.66
2    2017-11-15 10:30  12.66
3    2017-11-15 11:30  12.57
4    2017-11-15 14:00  12.73
5    2017-11-15 15:00  12.69
6    2017-11-16 10:30  12.69
7    2017-11-16 11:30  12.76
8    2017-11-16 14:00  12.75
9    2017-11-16 15:00  12.89
10   2017-11-17 10:30  12.59
11   2017-11-17 11:30  12.58
12   2017-11-17 14:00  12.43
13   2017-11-17 15:00  12.12
14   2017-11-20 10:30  12.26
15   2017-11-20 11:30  12.24
16   2017-11-20 14:00  12.32
17   2017-11-20 15:00  12.39
18   2017-11-21 10:30  12.44
19   2017-11-21 11:30  12.36
20   2017-11-21 14:00  12.29
21   2017-11-21 15:00  12.42
22   2017-11-22 10:30  12.47
23   2017-11-22 11:30  12.40
24   2017-11-22 14:00  12.28
25   2017-11-22 15:00  12.38
26   2017-11-23 10:30  12.34
27   2017-11-23 11:30  12.19
28   2017-11-23 14:00  12.62
29   2017-11-23 15:00  12.38
..                ...    ...
452  2018-05-04 14:00  13.97
453  2018-05-04 15:00  14.00
454  2018-05-07 10:30  13.95
455  2018-05-07 11:30  14.04
456  2018-05-07 14:00  14.07
457  2018-05-07 15:00  14.09
458  2018-05-08 10:30  13.89
459  2018-05-08 11:30  13.87
460  2018-05-08 14:00  13.90
461  2018-05-08 15:00  13.89
462  2018-05-09 10:30  13.90
463  2018-05-09 11:30  13.89
464  2018-05-09 14:00  13.88
465  2018-05-09 15:00  13.96
466  2018-05-10 10:30  13.96
467  2018-05-10 11:30  13.98
468  2018-05-10 14:00  13.93
469  2018-05-10 15:00  14.01
470  2018-05-11 10:30  14.01
471  2018-05-11 11:30  14.00
472  2018-05-11 14:00  14.02
473  2018-05-11 15:00  13.99
474  2018-05-14 10:30  14.15
475  2018-05-14 11:30  14.12
476  2018-05-14 14:00  14.02
477  2018-05-14 15:00  14.09
478  2018-05-15 10:30  14.13
479  2018-05-15 11:30  14.08
480  2018-05-15 14:00  14.17
481  2018-05-15 15:00  14.27

[482 rows x 2 columns]

In [ ]:
df = ts.get_tick_data('002408',date='2018-05-14')
df.head(100)

df = ts.get_realtime_quotes('002408') #Single stock symbol
df[['code','name','price','bid','ask','volume','amount','time']]

df = ts.get_today_ticks('002408')
df.head(10)